### ISSUE TITLE
Grid Error

### ISSUE THREAD

**Issue by DGMonster** [unitedgamereu/mayronui-gen5-bfa#6] opened 2018-07-25 19:58 UTC
Message: Interface\AddOns\Grid\Statuses\Stagger.lua:172: Usage: UnitDebuff("unit", [index][, "filter"])
Time: Wed Jul 25 21:58:06 2018
Count: 1
Stack: Interface\AddOns\Grid\Statuses\Stagger.lua:172: Usage: UnitDebuff("unit", [index][, "filter"])
[C]: in function `UnitDebuff'
Interface\AddOns\Grid\Statuses\Stagger.lua:172: in function `UpdateUnit'
Interface\AddOns\Grid\Statuses\Stagger.lua:143: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `SendMessage'
Interface\AddOns\Grid\Roster.lua:235: in function `UpdateRoster'
Interface\AddOns\Grid\Roster.lua:92: in function <Interface\AddOns\Grid\Roster.lua:82>
(tail call): ?
[C]: ?
...
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ace\AddOns\Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1191: in function <Interface\FrameXML\UIParent.lua:1089>

Locals: <none>

**Comment by Trockenbrot** [comment] 2018-07-25 21:30
Duplicate of #10 
should be fixed already

**Closed** 2018-07-25 21:30 UTC
Labels: bug
